### PR TITLE
Apply tests to test class

### LINKED ISSUE #45: Apply button makes selected tests appear
# Description
Currently, when tests are generated, they appear in the ToolWindow. However, the "Apply" button does not work.
This issue will focus on making it work and actually moving the files in a new test file in the tests folder.

# Definition of Done
* [x] #78
* [x]  Apply button should add the tests to a test file in tests folder.
* [x]  The extracted tests should only be those that the user has selected.

### PR DESCRIPTION
**Pull request by martinmladenov**
# Description of changes made
Allow the user to pick a test class to apply the selected tests to, and append the chosen test cases to the end of that class

# Why is merge request needed
Applying the test cases generated via TestGenie is a very nice feature so that the user doesn't have to copy them manually.

# Other notes
Closes #45

### CODE REVIEW

**Review by jzelenjak — COMMENTED** [review]
The feature you have implemented works for me.

I noticed though that with package-private fields it still marks them red (error). Is it a problem?

Also, the it can append tests multiple times. Maybe we want to not allow that?

The only thing that is missing in my opinion is that in order to append the files there must already be a class for tests. This is a bit confusing to the user who will have to create it manually and only then append the tests. Maybe we can give this option immediately when adding the tests to the file? (a separate issue though)

Other than that, good job!

**Comment by jzelenjak** [comment]
> @jzelenjak Thanks for the comments. What exactly do you mean by package-private fields - what is being marked as an error? Could you be a bit more specific?
> 
> About appending tests multiple times: I think that this is up to the user, since we shouldn't limit them in what they are allowed to do (and doing so would be very complex anyways). They could end up with equivalent tests by running the plugin multiple times as well, but there's not much we can do to prevent them from adding them to the test suite. We also shouldn't simply mark tests that have already been added to a file as "added" and never add them again, since a user could accidentally delete one of the tests they just added and might want to add it again.
> 
> Creating a test for class might indeed be a good idea, but we should be careful, since it gives users the impression that TestGenie can generate a complete test suite for the whole class, which is not the case. Tests should always be manually reviewed and augmented by a developer.

By *package-private* i mean if you don't put an access modifier, then it is only visible within a package, meaning that if in this case you put your tests into a file in another package, there will be errors, because they cannot be resolved

Imports are also broken, but that is fine in my opinion.

I agree with you about the second paragraph.

About the last point, i still think we have to add it, maybe in another issue, but otherwise it will be confusing to the user which we want to avoid.

**Comment by martinmladenov** [comment]
> By _package-private_ i mean if you don't put an access modifier, then it is only visible within a package, meaning that if in this case you put your tests into a file in another package, there will be errors, because they cannot be resolved

We can't really do anything about that, sadly - this is a consequence of allowing the user to insert test cases into any of their test classes. Preventing that would be very difficult and would likely be quite confusing to users if some of their test classes simply don't appear. In any case, it would be easy for a developer to fix such issues once they insert their tests.

**Review by kirilvasilev16 — APPROVED** [review]
I like how you made the file chooser for existing test suite to append tests to. I agree with yours and Jegors comments, but I think they can be addressed in separate issues as we are unsure yet if the client would like to have them implemented.

**Review by jzelenjak — APPROVED** [review]

**Pull request merged**
